// Generated by CoffeeScript 1.6.3
(function() {
  var url;

  url = require('url');

  exports.buildUrl = function(protocol, host, servicePath, version, formatEndPoint, key, query) {
    if (query == null) {
      query = {};
    }
    query.key = key;
    return url.format({
      protocol: protocol,
      host: host,
      pathname: [servicePath, version, formatEndPoint].join('/'),
      query: query
    });
  };

}).call(this);
